### ISSUE TITLE
Auto Spy ne fonctionne plus

### ISSUE THREAD

**Issue by seifounet** [Chewbaka69/sephiogame#1]
Bonjour,

après les dernieres MAJ la fonction autospy ne marche plus

j'ai essayé de corriger le bug sauf que je suis perdu

est ce possible de m'aider ?

**Comment by Chewbaka69** [comment]
SephiOgame est beaucoup trop ancien pour travailler dessus encore.
Je te conseille de te tourner vers d'autres bot.
